[package]
name = "fugue-fp"
version = "0.1.0"
authors = ["Sam Thomas <st@xv.ax>"]
edition = "2018"

[dependencies]
fugue-bv = { path = "../fugue-bv" }
fugue-ir = { path = "../fugue-ir" }
rug = { version = "1", features = ["float"] }
thiserror = "1"
