[package]
name = "fugue-fspec"
version = "0.2.5"
authors = ["Sam Thomas <st@xv.ax>"]
edition = "2021"
license = "MIT"
description = "A binary analysis framework written in Rust"
homepage = "https://fugue.re"

[features]
default = ["bigint"]

bigint = ["bigint-rug"]
bigint-malachite = ["fugue-ir/bigint-malachite", "fugue-sleigh/bigint-malachite"]
bigint-rug = ["fugue-ir/bigint-rug", "fugue-sleigh/bigint-rug"]

fixed-u64 = ["fugue-ir/fixed-u64", "fugue-sleigh/fixed-u64"]
fixed-u128 = ["fugue-ir/fixed-u128", "fugue-sleigh/fixed-u128"]

[dependencies]
bitflags = { version = "2", features = ["serde"] }
fugue-arch = { version = "0.2", path = "../fugue-arch" }
fugue-bytes = { version = "0.2", path = "../fugue-bytes" }
fugue-ir = { version = "0.2", path = "../fugue-ir", default-features = false }
fugue-sleigh = { version = "0.2", path = "../fugue-sleigh", default-features = false }
nom = "7"
regex = "1"
serde = "1"
serde_yaml = "0.9"
thiserror = "1"
