[package]
name = "fugue-fspec"
version = "0.2.0"
edition = "2021"

[dependencies]
bitflags = { version = "2", features = ["serde"] }
fugue-arch = { version = "0.2", path = "../fugue-arch" }
fugue-bytes = { version = "0.2", path = "../fugue-bytes" }
nom = "7"
regex = "1"
serde = "1"
serde_yaml = "0.9"
thiserror = "1"
