stages:
  - build

rust-latest:
  stage: build
  image: rust:latest
  script:
    - cargo build --verbose
    - cargo test --verbose

before_script:
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@git.simulacra.to/fugue/interval-tree.git".insteadOf "ssh://git@git.simulacra.to:10022/fugue/interval-tree"
