stages:
  - build

rust-latest:
  stage: build
  image: rust:latest
  script:
    - cargo build --verbose
    - cargo test --verbose

before_script:
  - apt-get update -y
  - apt-get install capnproto openssh-client -y
  - eval $(ssh-agent -s)
  - echo "$FUGUE_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - mkdir -p ~/.cargo
  - echo '[registries]\nfugue = { index = "ssh://git@github.com/fugue-re/fugue-registry.git" }' >> ~/.cargo/config
  - cat ~/.cargo/config
  - cargo login --registry=fugue "$FUGUE_REGISTRY_TOKEN"
