stages:
  - build

rust-latest:
  stage: build
  image: rust:latest
  script:
    - cargo build --verbose
    - cargo test --verbose

before_script:
  - apt-get update -y
  - apt-get install capnproto -y
  - git clone git@github.com:fugue-re/fugue-registry.git
  - mkdir -p ~/.cargo
  - echo '[registries]' >> ~/.cargo/config.toml
  - echo 'fugue = { index = "https://github.com/fugue-re/fugue-registry" }' >> ~/.cargo/config.toml
  - cargo login --registry=fugue "$FUGUE_REGISTRY_TOKEN"
