stages:
  - build

rust-latest:
  stage: build
  image: rust:latest
  script:
    - cargo build --verbose
    - cargo test --verbose

before_script:
  - apt-get update
  - apt-get install capnproto
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@git.simulacra.to/".insteadOf "ssh://git@git.simulacra.to:10022/"
