stages:
  - build

rust-latest:
  stage: build
  image: rust:latest
  script:
    - cargo build --verbose
    - cargo test --verbose

before_script:
  - apt-get update -y
  - apt-get install capnproto -y
  - mkdir -p $HOME/.cargo
  - echo '[registries]\nfugue = { index = "ssh://git@github.com/fugue-re/fugue-registry.git" }' > $HOME/.cargo/config
  - echo "[registries.fugue]\ntoken = \"${FUGUE_REGISTRY_TOKEN}\"" > $HOME/.cargo/credentials
