[workspace]
members = [
  "fugue",
  "fugue-arch",
  "fugue-bytes",
  "fugue-bv",
  "fugue-core",
  "fugue-fp",
  "fugue-ir",
  "fugue-state",
  "fugue-state-derive",
]
resolver = "2"

[profile.bench]
debug = true
