[package]
name = "fugue-arch"
version = "0.1.1"
authors = ["Sam Thomas <st@xv.ax>"]
edition = "2018"
license = "MIT"

[dependencies]
fugue-bytes = { path = "../fugue-bytes", version = "0.1", registry = "fugue" }
thiserror = "1"
unicase = "2.6"
