[package]
name = "fugue-arch"
version = "0.2.0"
authors = ["Sam Thomas <st@xv.ax>"]
edition = "2018"
license = "MIT"

[dependencies]
fugue-bytes = { path = "../fugue-bytes", version = "0.2", registry = "fugue" }
thiserror = "1"
unicase = "2.6"
