[package]
name = "fugue-db"
version = "0.2.18"
authors = ["Sam Thomas <st@xv.ax>"]
edition = "2021"
build = "build.rs"
license = "MIT"
description = "A binary analysis framework written in Rust"
homepage = "https://fugue.re"

[features]
default = ["bigint"]

bigint = ["bigint-rug"]
bigint-malachite = ["fugue-ir/bigint-malachite"]
bigint-rug = ["fugue-ir/bigint-rug"]

fixed-u64 = ["fugue-ir/fixed-u64"]
fixed-u128 = ["fugue-ir/fixed-u128"]

[dependencies]
fugue-arch = { path = "../fugue-arch", version = "0.2" }
fugue-bytes = { path = "../fugue-bytes", version = "0.2" }
fugue-ir = { path = "../fugue-ir", version = "0.2", default-features = false }

educe = "0.4"
flatbuffers = "24.3.25"
fs_extra = "1.2"
iset = { version = "0.3", package = "fugue-iset" }
ouroboros = "0.9"

serde = { version = "1", features = ["derive"] }
tempfile = "3"
thiserror = "1"
unicase = "2.6"
which = "4"
url = "2.2"

[build-dependencies]
flatcc = "24.3.25"

[lints.rust]
mismatched_lifetime_syntaxes = "allow"
