[package]
name = "fugue-emu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
fugue = { version = "0.3.0", path = "../fugue-core" }
multi_key_map = { version = "0.3.0" }
anyhow = "1"
thiserror = "1"