[package]
name = "fugue-lifter-arm"
version = "0.3.0"
edition = "2021"
build = "build.rs"

[features]
arm-be = []
arm-le = []
default = ["arm-be", "arm-le"]

[dependencies]
fugue-lifter-runtime = { version = "0.3", path = "../fugue-lifter-runtime" }

[build-dependencies]
fugue-lifter-codegen = { version = "0.3", path = "../fugue-lifter-codegen" }
