[package]
name = "fugue-bytes"
version = "0.2.1"
authors = ["Sam Thomas <st@xv.ax>"]
edition = "2021"
license = "MIT"

[dependencies]
byteorder = "1"
paste = "1"
serde = { version = "1", features = ["derive"] }
ux = "0.1"
